### ISSUE TITLE
Can't read Wago Answer - Error: Network Error

### ISSUE THREAD

**Issue by Anubiz0411** [WeakAuras/WeakAuras-Companion#1234]
**Operating System:**
- [ X ] Windows
- [ ] Mac
- [ ] Linux

**Companion Version:**
```
3.3.4
```

**Companion App Console Log:**
```
app.2e94e2cb.js:17 {"message":"Network Error","name":"Error","stack":"Error: Network Error\n    at O.exports (app://./js/chunk-vendors.06f3698e.js:13:4813)\n    at XMLHttpRequest.A.onerror (app://./js/chunk-vendors.06f3698e.js:62:55093)","config":{"url":"https://data.wago.io/api/check/weakauras","method":"get","headers":{"Accept":"application/json, text/plain, */*","Identifier":"a0ba03db","api-key":"82UdlPNSfApkOc4LQU2SJnbzGP5935cvkgUokxqE"},"params":{"ids":"sltrinkets,slraid2,SL-Dungeons,SkBHabbrQ,HJnU6WWrX,rkfLTbbSX,rkvhCRT7X,HkdpgyHH7,CooldownsOnNameplate,H1hyTwAE7,1ctv3b91K,r11CnDRVQ,F1dMAfhui,Hk8Rx1rSX,Bzs5CPs9G,H1NybJHB7,cyRj6ikQz,M+Timer,Sk5C2PRE7,slcotank2,YBa2GlIu5,deHBW0Mpe,TazaveshConsole,it6fAV41Z,B1H06AUNM,rxglPvUdy,N5ollwhXn,_PCyfyfoR,explosiveorbs,klC4qqHaF,04YHZsxIO,SoDAnimaPowers"},"transformRequest":[null],"transformResponse":[null],"timeout":15000,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"crossdomain":true}}
app.2e94e2cb.js:17 promisesWagoCallsComplete
app.2e94e2cb.js:17 promisesWagoDataCallsComplete
app.2e94e2cb.js:17 no data received for sltrinkets
app.2e94e2cb.js:17 no data received for slraid2
app.2e94e2cb.js:17 no data received for SL-Dungeons
app.2e94e2cb.js:17 no data received for SkBHabbrQ
app.2e94e2cb.js:17 no data received for HJnU6WWrX
app.2e94e2cb.js:17 no data received for rkfLTbbSX
app.2e94e2cb.js:17 no data received for rkvhCRT7X
app.2e94e2cb.js:17 no data received for HkdpgyHH7
app.2e94e2cb.js:17 no data received for CooldownsOnNameplate
app.2e94e2cb.js:17 no data received for H1hyTwAE7
app.2e94e2cb.js:17 no data received for 1ctv3b91K
app.2e94e2cb.js:17 no data received for r11CnDRVQ
app.2e94e2cb.js:17 no data received for F1dMAfhui
app.2e94e2cb.js:17 no data received for Hk8Rx1rSX
app.2e94e2cb.js:17 no data received for Bzs5CPs9G
app.2e94e2cb.js:17 no data received for H1NybJHB7
app.2e94e2cb.js:17 no data received for cyRj6ikQz
app.2e94e2cb.js:17 no data received for M+Timer
app.2e94e2cb.js:17 no data received for Sk5C2PRE7
app.2e94e2cb.js:17 no data received for slcotank2
app.2e94e2cb.js:17 no data received for YBa2GlIu5
app.2e94e2cb.js:17 no data received for deHBW0Mpe
app.2e94e2cb.js:17 no data received for TazaveshConsole
app.2e94e2cb.js:17 no data received for it6fAV41Z
app.2e94e2cb.js:17 no data received for B1H06AUNM
app.2e94e2cb.js:17 no data received for rxglPvUdy
app.2e94e2cb.js:17 no data received for N5ollwhXn
app.2e94e2cb.js:17 no data received for _PCyfyfoR
app.2e94e2cb.js:17 no data received for explosiveorbs
app.2e94e2cb.js:17 no data received for klC4qqHaF
app.2e94e2cb.js:17 no data received for 04YHZsxIO
app.2e94e2cb.js:17 no data received for SoDAnimaPowers
app.2e94e2cb.js:17 writeAddonData
chunk-vendors.06f3698e.js:62 GET https://data.wago.io/api/check/weakauras?ids=sltrinkets,slraid2,SL-Dungeons,SkBHabbrQ,HJnU6WWrX,rkfLTbbSX,rkvhCRT7X,HkdpgyHH7,CooldownsOnNameplate,H1hyTwAE7,1ctv3b91K,r11CnDRVQ,F1dMAfhui,Hk8Rx1rSX,Bzs5CPs9G,H1NybJHB7,cyRj6ikQz,M%2BTimer,Sk5C2PRE7,slcotank2,YBa2GlIu5,deHBW0Mpe,TazaveshConsole,it6fAV41Z,B1H06AUNM,rxglPvUdy,N5ollwhXn,_PCyfyfoR,explosiveorbs,klC4qqHaF,04YHZsxIO,SoDAnimaPowers net::ERR_FAILED
(anonymous) @ chunk-vendors.06f3698e.js:62
O.exports @ chunk-vendors.06f3698e.js:62
O.exports @ chunk-vendors.06f3698e.js:17
Promise.then (async)
r.request @ chunk-vendors.06f3698e.js:1
r.<computed> @ chunk-vendors.06f3698e.js:1
(anonymous) @ chunk-vendors.06f3698e.js:6
(anonymous) @ app.2e94e2cb.js:17
compareSVwithWago @ app.2e94e2cb.js:17
refresh @ app.2e94e2cb.js:1
Mt @ chunk-vendors.06f3698e.js:11
S @ chunk-vendors.06f3698e.js:11
Mt @ chunk-vendors.06f3698e.js:11
f.$emit @ chunk-vendors.06f3698e.js:11
callback @ app.2e94e2cb.js:1
click @ app.2e94e2cb.js:1
Mt @ chunk-vendors.06f3698e.js:11
S @ chunk-vendors.06f3698e.js:11
Ns.ae._wrapper @ chunk-vendors.06f3698e.js:11
chunk-vendors.06f3698e.js:62 XHR failed loading: GET "https://data.wago.io/api/check/weakauras?ids=sltrinkets,slraid2,SL-Dungeons,SkBHabbrQ,HJnU6WWrX,rkfLTbbSX,rkvhCRT7X,HkdpgyHH7,CooldownsOnNameplate,H1hyTwAE7,1ctv3b91K,r11CnDRVQ,F1dMAfhui,Hk8Rx1rSX,Bzs5CPs9G,H1NybJHB7,cyRj6ikQz,M%2BTimer,Sk5C2PRE7,slcotank2,YBa2GlIu5,deHBW0Mpe,TazaveshConsole,it6fAV41Z,B1H06AUNM,rxglPvUdy,N5ollwhXn,_PCyfyfoR,explosiveorbs,klC4qqHaF,04YHZsxIO,SoDAnimaPowers".
```

**WeakAuras Version:**
```
3.7.3
```

**Describe the bug**
```
Can't read Wago Answer - Error: Network Error
```

**To Reproduce**
1. Go to 'WA Companion'
2. See error

**Screenshots**
![imagen](https://user-images.githubusercontent.com/18010875/146685276-f5070c41-9ff0-4c99-8f9c-0269dadfc4ce.png)

**Include a .zip file containing:**

[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras-Companion/files/7741276/WeakAuras.zip)

**Comment by mrbuds** [comment]
This is not a bug in the app, wago or your connection had a temporary issue.
