### ISSUE TITLE
Blank screen on load with appimage

### ISSUE THREAD

**Issue by peoii** [WeakAuras/WeakAuras-Companion#1376]
**Operating System:**
- [ ] Windows
- [ ] Mac
- [X] Linux

**Companion Version:**
```
4.0.0-beta4
```

**Companion App Console Log:**
```
Uncaught Error: 
Something went wrong installing the "sharp" module

libvips-cpp.so.42: cannot open shared object file: No such file or directory

Possible solutions:
- Install with the --verbose flag and look for errors: "npm install --ignore-scripts=false --verbose sharp"
- Install for the current linux-x64 runtime: "npm install --platform=linux --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/tmp/.mount_WeakAuVrNMGr/resources/app.asar/node_modules/sharp/lib/sharp.js:31:9)
    at Object.<anonymous> (/tmp/.mount_WeakAuVrNMGr/resources/app.asar/node_modules/sharp/lib/sharp.js:34:3)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function.i._load (node:electron/js2c/renderer_init:33:356)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
```

**WeakAuras Version:**
```
/run print(WeakAuras.versionString) in-game.
```

**Describe the bug**
Upon attempt at launching anything newer than 4.0.0-beta1 there is nothing but a black background pane displayed.  4.0.0-beta1 works normally

**To Reproduce**
This is on-launch via the AppImage on a machine without NPM installed.

**Expected behavior**
For it to load as expected.

**Screenshots**
![2022-05-01_09-23](https://user-images.githubusercontent.com/68097/166145830-6548d9db-31ea-453d-93ad-b19a696ae1a3.png)

**Include a .zip file containing:**
[wa-comp.zip](https://github.com/WeakAuras/WeakAuras-Companion/files/8598874/wa-comp.zip)

**Comment by mrbuds** [comment]
Thanks for the report, a potential fix was added but i couldn't test, could you try beta5?
