### ISSUE TITLE
The app couldn't find my game's folder

### ISSUE THREAD

**Issue by gabrielbioinfo** [WeakAuras/WeakAuras-Companion#2041]
**Operating System:**
- [ ] Windows

**Companion Version:**
```
5.1.1
```

**Companion App Console Log:**
```
index-fec47689.js:11 TypeError: Cannot read properties of undefined (reading 'length')
    at dn (index-fec47689.js:2:13028)
    at dn (index-fec47689.js:2:13046)
    at S_ (index-fec47689.js:2:14929)
    at index-fec47689.js:11:7430
```

**Describe the bug**
The app couldn't find my game's folder

**To Reproduce**
1. Go to 'Finish Setup'
2. Click on 'Game Settings'
3. Select wow folder
4. It doesn't validate and always throws a error

**Screenshots**
![image](https://github.com/WeakAuras/WeakAuras-Companion/assets/3164939/e815074a-6d7e-462f-b983-ec9f94896418)

**Comment by mrbuds** [comment]
Do you have weakauras installed?
