### ISSUE TITLE
Weakaura companion does not diplay an update for a specific WA

### ISSUE THREAD

**Issue by Moowalker** [WeakAuras/WeakAuras-Companion#2065]
**Operating System:**  Windows

**Companion Version:** 5.1.1

**Companion App Console Log:**
```
index-fec47689.js:6 userDataPath C:\Users\Moowalker\AppData\Roaming\weakauras-companion
index-fec47689.js:74 buildAccountList
index-fec47689.js:95 validateWowPath
index-fec47689.js:95 buildVersionList
index-fec47689.js:74 buildAccountList
index-fec47689.js:2 TypeError: Cannot read properties of undefined (reading 'milliseconds')
    at Oe.toMillis (index-fec47689.js:6:40707)
    at Oe.valueOf (index-fec47689.js:6:40845)
    at index-fec47689.js:95:57760
    at Array.sort (<anonymous>)
    at Proxy.aurasSortedForView (index-fec47689.js:97:15243)
    at Ul.run (index-fec47689.js:2:4371)
    at get value [as value] (index-fec47689.js:2:12684)
    at Object.get [as aurasSortedForView] (index-fec47689.js:2:24184)
    at Object.get (index-fec47689.js:2:22411)
    at Proxy.mP (index-fec47689.js:97:23118)
y_ @ index-fec47689.js:2
index-fec47689.js:2 TypeError: Cannot read properties of undefined (reading 'milliseconds')
    at Oe.toMillis (index-fec47689.js:6:40707)
    at Oe.valueOf (index-fec47689.js:6:40845)
    at Proxy.olderThan30s (index-fec47689.js:11:17627)
    at Proxy.Jk (index-fec47689.js:11:20175)
    at ba (index-fec47689.js:2:16102)
    at Ul.V [as fn] (index-fec47689.js:2:36980)
    at Ul.run (index-fec47689.js:2:4371)
    at z.update (index-fec47689.js:2:37259)
    at le (index-fec47689.js:2:37285)
    at Ce (index-fec47689.js:2:36095)
y_ @ index-fec47689.js:2
index-fec47689.js:2 TypeError: Cannot read properties of undefined (reading 'milliseconds')
    at Oe.toMillis (index-fec47689.js:6:40707)
    at Oe.valueOf (index-fec47689.js:6:40845)
    at Proxy.olderThan30s (index-fec47689.js:11:17627)
    at Proxy.Jk (index-fec47689.js:11:20175)
    at ba (index-fec47689.js:2:16102)
    at Ul.V [as fn] (index-fec47689.js:2:36511)
    at Ul.run (index-fec47689.js:2:4371)
    at z.update (index-fec47689.js:2:37259)
    at De (index-fec47689.js:2:36251)
    at se (index-fec47689.js:2:35906)
y_ @ index-fec47689.js:2
index-fec47689.js:97 Creating default directory
index-fec47689.js:97 promisesWagoCallsComplete
index-fec47689.js:97 promisesWagoDataCallsComplete
index-fec47689.js:97 no data received for M+Timer
index-fec47689.js:97 no data received for M+LevelDisplay
index-fec47689.js:97 no data received for Tamas-Catch-&-Release
index-fec47689.js:97 no data received for Cl-Cm6nyb
index-fec47689.js:97 no data received for dfdungeons
index-fec47689.js:97 no data received for LiquidAberrus
index-fec47689.js:97 no data received for LiquidAnchors
index-fec47689.js:97 no data received for 5skqHEtfd
index-fec47689.js:97 no data received for 21o-Hvmjh
index-fec47689.js:97 no data received for fkKJNBIuG
index-fec47689.js:97 no data received for GDUFhpEAE
index-fec47689.js:97 no data received for TamasProfessionmodule
index-fec47689.js:97 no data received for ShnT6Yih6
index-fec47689.js:20 writeAddonData
index-fec47689.js:40 WeakAuras.toc has version: 100105
index-fec47689.js:95 Error testing WeakAuras SV access
{"errno":-4058,"syscall":"access","code":"ENOENT","path":"C:\\Games\\World of Warcraft\\_retail_\\WTF\\Account\\1616569#1\\SavedVariables\\WeakAuras.lua"}
index-fec47689.js:95 Error testing Plater SV access
{"errno":-4058,"syscall":"access","code":"ENOENT","path":"C:\\Games\\World of Warcraft\\_retail_\\WTF\\Account\\1616569#1\\SavedVariables\\Plater.lua"}
index-fec47689.js:95 Error testing WeakAuras SV access
{"errno":-4058,"syscall":"access","code":"ENOENT","path":"C:\\Games\\World of Warcraft\\_retail_\\WTF\\Account\\105773042#2\\SavedVariables\\WeakAuras.lua"}
index-fec47689.js:95 Error testing Plater SV access
{"errno":-4058,"syscall":"access","code":"ENOENT","path":"C:\\Games\\World of Warcraft\\_retail_\\WTF\\Account\\105773042#2\\SavedVariables\\Plater.lua"}
index-fec47689.js:95 Error testing WeakAuras SV access
{"errno":-4058,"syscall":"access","code":"ENOENT","path":"C:\\Games\\World of Warcraft\\_retail_\\WTF\\Account\\1616569#1\\SavedVariables\\WeakAuras.lua"}
index-fec47689.js:95 Error testing Plater SV access
{"errno":-4058,"syscall":"access","code":"ENOENT","path":"C:\\Games\\World of Warcraft\\_retail_\\WTF\\Account\\1616569#1\\SavedVariables\\Plater.lua"}
index-fec47689.js:95 Error testing WeakAuras SV access
{"errno":-4058,"syscall":"access","code":"ENOENT","path":"C:\\Games\\World of Warcraft\\_retail_\\WTF\\Account\\401982847#2\\SavedVariables\\WeakAuras.lua"}
index-fec47689.js:95 Error testing Plater SV access
{"errno":-4058,"syscall":"access","code":"ENOENT","path":"C:\\Games\\World of Warcraft\\_retail_\\WTF\\Account\\401982847#2\\SavedVariables\\Plater.lua"}
index-fec47689.js:95 Error testing WeakAuras SV access
{"errno":-4058,"syscall":"access","code":"ENOENT","path":"C:\\Games\\World of Warcraft\\_retail_\\WTF\\Account\\1616569#9\\SavedVariables\\WeakAuras.lua"}
index-fec47689.js:95 Error testing Plater SV access
{"errno":-4058,"syscall":"access","code":"ENOENT","path":"C:\\Games\\World of Warcraft\\_retail_\\WTF\\Account\\1616569#9\\SavedVariables\\Plater.lua"}
```

**WeakAuras Version:** 5.7.0

**WeakAuras Errors:** No WA errors

**Describe the bug**
WA companion does not display an update for this WA: https://wago.io/21o-Hvmjh (maybe others too). The ingame version is 64 but the one in Wago is 66

**Expected behavior:** The companion app should display the update

**Screenshots**
![image](https://github.com/WeakAuras/WeakAuras-Companion/assets/14836857/65e7408e-70f0-4c7d-9591-dcd80e6635a1)
![image](https://github.com/WeakAuras/WeakAuras-Companion/assets/14836857/c1e5abe1-5f4c-4eb7-b822-b20666525045)

First screenshot is the wago uid and second is the ingame uid.

Also the WA companion

![image](https://github.com/WeakAuras/WeakAuras-Companion/assets/14836857/417f171c-4ebd-41a3-bc5c-0f752ac12e09)

**Include a .zip file containing:**
[files.zip](https://github.com/WeakAuras/WeakAuras-Companion/files/12540158/files.zip)

**Comment by mrbuds** [comment]
https://github.com/WeakAuras/WeakAuras-Companion/commit/77901b5f81d434e87d71d1b5f5e1899f99633bf3 fix this issue
