### ISSUE TITLE
[Feature Request] Taskbar icon flash on download complete

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras-Companion#223]
when the download of the client update has finished and the app is in the background, flash the taskbar icon on Windows

**Comment by mrbuds** [comment]
I don't know enough how windows 10 api works, but for me the icon is hidden and i have to click the ^ arrow to see it and in that case which i suppose i very common flashing it wouldn't help achieve your goal.
Also there is already a notification for that
![img](https://i.imgur.com/ZtN0spU.png)

**Comment by Stanzilla** [comment]
We could add a restart button to that notification via https://electronjs.org/docs/tutorial/notifications#advanced-notifications. Also why is the icon so small :/

**Comment by mrbuds** [comment]
Mhmm i'v been there already https://github.com/felixrieseberg/electron-windows-notifications/issues/11

Now i have a different error but still can't install the package and it doesn't seem to be maintained
```
[4/5] Building fresh packages...
error C:\Users\buds\Documents\GitHub\wa-companion\node_modules\@nodert-win10-cu\windows.foundation: Command failed.
Exit code: 1
```

**Comment by mrbuds** [comment]
If you have an idea how to fix that
```
c:\users\buds\documents\github\wa-companion\node_modules\@nodert-win10-cu\windows.applicationmodel\_nodert_generated.cpp : fatal error C1107: could not find assembly 'platform.winmd': please specify the assembly search path using /AI or by setting the LIBPATH environment variable [C:\Users\buds\Documents\GitHub\wa-companion\node_modules\@nodert-win10-cu\windows.applicationmodel\build\binding.vcxproj]
c:\users\buds\documents\github\wa-companion\node_modules\@nodert-win10-cu\windows.applicationmodel\opaquewrapper.cpp : fatal error C1107: could not find assembly 'platform.winmd': please specify the assembly search path using /AI or by setting the LIBPATH environment variable [C:\Users\buds\Documents\GitHub\wa-companion\node_modules\@nodert-win10-cu\windows.applicationmodel\build\binding.vcxproj]
c:\users\buds\documents\github\wa-companion\node_modules\@nodert-win10-cu\windows.applicationmodel\nodertutils.cpp : fatal error C1107: could not find assembly 'platform.winmd': please specify the assembly search path using /AI or by setting the LIBPATH environment variable [C:\Users\buds\Documents\GitHub\wa-companion\node_modules\@nodert-win10-cu\windows.applicationmodel\build\binding.vcxproj]
c:\program files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.cc : fatal error C1107: could not find assembly 'platform.winmd': please specify the assembly search path using /AI or by setting the LIBPATH environment variable [C:\Users\buds\Documents\GitHub\wa-companion\node_modules\@nodert-win10-cu\windows.applicationmodel\build\binding.vcxproj]
c:\users\buds\documents\github\wa-companion\node_modules\@nodert-win10-cu\windows.applicationmodel\collectionsconverterutils.cpp : fatal error C1107: could not find assembly 'platform.winmd': please specify the assembly search path using /AI or by setting the LIBPATH environment variable [C:\Users\buds\Documents\GitHub\wa-companion\node_modules\@nodert-win10-cu\windows.applicationmodel\build\binding.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\buds\Documents\GitHub\wa-companion\node_modules\@nodert-win10-cu\windows.applicationmodel
```

**Comment by mrbuds** [comment]
trying install last win10 sdk for x86 and amd64 from https://developer.microsoft.com/en-us/windows/downloads/sdk-archive ...

**Comment by mrbuds** [comment]
Improved Notification's icon but i can't get how to install nodert-win10 to do more with notifications, their node package have too much bugs and spent too much time on it already.
Will check if the situation has improved in a few months...
