### ISSUE TITLE
Previous WAs still in Companion

### ISSUE THREAD

**Issue by frentzn** [WeakAuras/WeakAuras-Companion#2603]
**Operating System:**
- [x ] Windows
- [ ] Mac
- [ ] Linux

**Companion Version:**
```
5.2.7
```

**Companion App Console Log:**
```
index-CA-za9nQ.js:32 userDataPath C:\Users\Robin\AppData\Roaming\weakauras-companion
index-CA-za9nQ.js:51 validateWowPath
index-CA-za9nQ.js:51 Error: ENOENT: no such file or directory, access 'C:\Program Files (x86)\World of Warcraft\_retail_\Data'
    at Object.accessSync (node:fs:244:11)
    at t.accessSync (node:electron/js2c/node_init:2:9362)
    at _f (index-CA-za9nQ.js:51:48028)
    at config.wowpath.value (index-CA-za9nQ.js:112:52602)
    at xi (index-CA-za9nQ.js:14:38)
    at Ln (index-CA-za9nQ.js:14:109)
    at a.call (index-CA-za9nQ.js:14:26598)
    at b (index-CA-za9nQ.js:10:15833)
    at xi (index-CA-za9nQ.js:14:46)
    at Qf (index-CA-za9nQ.js:14:1835)
index-CA-za9nQ.js:51 validateWowPath
index-CA-za9nQ.js:51 buildVersionList
index-CA-za9nQ.js:22 buildAccountList
index-CA-za9nQ.js:51 validateWowPath
index-CA-za9nQ.js:51 buildVersionList
index-CA-za9nQ.js:22 buildAccountList
index-CA-za9nQ.js:113 Creating default directory
index-CA-za9nQ.js:22 buildAccountList
index-CA-za9nQ.js:31 promisesWagoCallsComplete
index-CA-za9nQ.js:31 promisesWagoDataCallsComplete
index-CA-za9nQ.js:54 writeAddonData
index-CA-za9nQ.js:74 WeakAuras.toc has version: 110002
index-CA-za9nQ.js:51 Backup: Plater-_retail_#450046499#2-20240925132442.zip saved
index-CA-za9nQ.js:51 Backup: WeakAuras-_retail_#450046499#2-20240925132442.zip saved
index-CA-za9nQ.js:31 promisesWagoCallsComplete
index-CA-za9nQ.js:31 promisesWagoDataCallsComplete
index-CA-za9nQ.js:54 writeAddonData
index-CA-za9nQ.js:74 WeakAuras.toc has version: 110002
index-CA-za9nQ.js:31 promisesWagoCallsComplete
index-CA-za9nQ.js:31 promisesWagoDataCallsComplete
index-CA-za9nQ.js:54 writeAddonData
index-CA-za9nQ.js:74 WeakAuras.toc has version: 110002
index-CA-za9nQ.js:31 promisesWagoCallsComplete
index-CA-za9nQ.js:31 promisesWagoDataCallsComplete
index-CA-za9nQ.js:54 writeAddonData
index-CA-za9nQ.js:74 WeakAuras.toc has version: 110002

```

**WeakAuras Version:**
```
5.17.1
```

**WeakAuras Errors:**
```
none
```

**Describe the bug**
Previous WeakAuras which I used months ago are still shown in the WeakAura Companion App. I dont have them installed ingame.

**To Reproduce**
.

**Expected behavior**
How can I remove them to be not shown in Companion and also not ingame?

**Screenshots**
.

**Include a .zip file containing:**
`%programfiles%\World of Warcraft\_retail_\WTF\Account\<AccountName>\SavedVariables\WeakAuras.lua`
AND
`[attachments.zip](https://github.com/user-attachments/files/17130137/attachments.zip)config.json`

**Comment by ChrisKoenig** [comment]
I'm having exactly the same issue. I deleted a WA, then restarted both WOW and the Companion, and it still shows an update is available.
