### ISSUE TITLE
Beta updater error

### ISSUE THREAD

**Issue by Musouv** [WeakAuras/WeakAuras-Companion#528]
**Operating System:**
- [x] Windows
- [ ] Mac
- [ ] Linux

**Companion Version:**
```
2.0.0
```
**To Reproduce**
1. Go to 'Settings'
2. Click on 'Use Companion Beta Channel'
3. See error (screenshots) that causes endless loop for checking updates
4. Uncheck 'Use Companion Beta Channel'
5. checking updates completes correctly
6. repeat step 2-5

**Expected behavior**
App would either update or finish checking for updates

**Screenshots**
![](https://i.imgur.com/8Apz2Pe.png)
![](https://i.imgur.com/HVTHAzf.png)

**Comment by mrbuds** [comment]
Hey, could you add the console log (ctrl+shift+I) and a zip of your %appdata%\weakauras-companion\log.log ?

**Comment by Musouv** [comment]
pressing that key combination does not do anything in my WA client, but here is the log
[log.zip](https://github.com/WeakAuras/WeakAuras-Companion/files/3999193/log.zip)

**Comment by mrbuds** [comment]
```
[2019-12-24 13:53:48.892] [warn] Error on remove temp update file: Error: EPERM: operation not permitted, unlink 'C:\Users\Vincent Chiu\AppData\Local\weakauras-companion-updater\pending\temp-WeakAuras-Companion-Setup-2.0.1-beta1.exe'
[2019-12-24 13:53:48.903] [info] Download block maps (old: "https://github.com/WeakAuras/WeakAuras-Companion/releases/download/v2.0.0/WeakAuras-Companion-Setup-2.0.0.exe.blockmap", new: https://github.com/WeakAuras/WeakAuras-Companion/releases/download/v2.0.1-beta1/WeakAuras-Companion-Setup-2.0.1-beta1.exe.blockmap)
[2019-12-24 13:53:49.102] [error] Cannot download differentially, fallback to full download: Error: Redirect was cancelled
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2558:23)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
[2019-12-24 13:53:49.894] [error] Error: Error: Redirect was cancelled
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2558:23)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)

```

**Comment by mrbuds** [comment]
It looks like an upstream (Electron) bug

**Comment by Stanzilla** [comment]
Oh great, I love those

**Comment by Bpsmooth** [comment]
I am uploading my log as well, since I have the same issue. hope it helps! Also not sure if I did it right, but I think it was you need.
[log.zip](https://github.com/WeakAuras/WeakAuras-Companion/files/3999475/log.zip)

**Comment by RaZz0r65** [comment]
i am uploading my log also as im having the same problem

[log.zip](https://github.com/WeakAuras/WeakAuras-Companion/files/4003173/log.zip)

**Comment by Aurielli** [comment]
Here is mine aswell. 
[log.zip](https://github.com/WeakAuras/WeakAuras-Companion/files/4005271/log.zip)

**Comment by mrbuds** [comment]
Thanks for the logs, it helped track the error to this ticket https://github.com/electron/electron/issues/21566 for which a patch was made 20h ago from now.

Unfortunately, all users of companion 2.0.0 won't be able to update to next version with auto-updater.

**Comment by mrbuds** [comment]
I reopen this ticket until issue is fixed upstream and we make a release including the fix.

If have the issue and read this, please download last version from <https://github.com/WeakAuras/WeakAuras-Companion/releases>
