### ISSUE TITLE
Toast error somewhere in compareSVwithWago()

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras-Companion#95]
**Operating System:**
- [x] Windows
- [ ] Mac
- [ ] Linux

**Companion Version:**
1.1.4-beta3

**Companion App Console Log:**
```
C:\Users\buds\AppData\Local\Programs\weakauras-companion\resources\app.asar\node_modules\vue-toasted\dist\vue-toasted.min.js:1 Uncaught (in promise) DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided must not be empty.
    at C:\Users\buds\AppData\Local\Programs\weakauras-companion\resources\app.asar\node_modules\vue-toasted\dist\vue-toasted.min.js:1:21680
    at Array.forEach (<anonymous>)
    at p (C:\Users\buds\AppData\Local\Programs\weakauras-companion\resources\app.asar\node_modules\vue-toasted\dist\vue-toasted.min.js:1:21648)
    at e.a (C:\Users\buds\AppData\Local\Programs\weakauras-companion\resources\app.asar\node_modules\vue-toasted\dist\vue-toasted.min.js:1:25180)
    at c (C:\Users\buds\AppData\Local\Programs\weakauras-companion\resources\app.asar\node_modules\vue-toasted\dist\vue-toasted.min.js:1:4249)
    at t.error (C:\Users\buds\AppData\Local\Programs\weakauras-companion\resources\app.asar\node_modules\vue-toasted\dist\vue-toasted.min.js:1:3681)
    at i.message (file:///C:/Users/buds/AppData/Local/Programs/weakauras-companion/resources/app.asar/dist/electron/renderer.js:1:229641)
    at file:///C:/Users/buds/AppData/Local/Programs/weakauras-companion/resources/app.asar/dist/electron/renderer.js:1:234977
(anonymous) @ C:\Users\buds\AppData\Local\Programs\weakauras-companion\resources\app.asar\node_modules\vue-toasted\dist\vue-toasted.min.js:1
p @ C:\Users\buds\AppData\Local\Programs\weakauras-companion\resources\app.asar\node_modules\vue-toasted\dist\vue-toasted.min.js:1
e.a @ C:\Users\buds\AppData\Local\Programs\weakauras-companion\resources\app.asar\node_modules\vue-toasted\dist\vue-toasted.min.js:1
c @ C:\Users\buds\AppData\Local\Programs\weakauras-companion\resources\app.asar\node_modules\vue-toasted\dist\vue-toasted.min.js:1
error @ C:\Users\buds\AppData\Local\Programs\weakauras-companion\resources\app.asar\node_modules\vue-toasted\dist\vue-toasted.min.js:1
message @ renderer.js:1
(anonymous) @ renderer.js:1
Promise.catch (async)
(anonymous) @ renderer.js:1
readFileAfterClose @ internal/fs/read_file_context.js:53
```

**Describe the bug**
Saw this error in console, with the fetching icon stuck rolling, which means before `this.fetching` is set to false

**To Reproduce**
start app and .. wait ?

**Comment by mrbuds** [comment]
fixed with 1.1.5
